### ISSUE TITLE
Hi, is any explanation about the scale_fix in the RangeBN

### ISSUE THREAD

**Issue by blueardour** [eladhoffer/convNet.pytorch#13]
A fix is added in the RangeBN for the scale:
scale_fix = (0.5 * 0.35) * (1 + (math.pi * math.log(4)) **  0.5) / ((2 * math.log(y.size(-1))) ** 0.5)

(2lng(n)) ** 0.5 is explained in the paper. However where do the 0.5 / 0.35/ pie*ln(4) come from?

**Comment by I-Doctor** [comment]
I have the same question, have you got any idea?
